name: petapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  rxdart: ^0.26.0
  cached_network_image: ^3.1.0
  dropdown_button2: ^2.1.3
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.9
  # google_fonts: ^2.1.1
  # badges: ^2.0.2
  flutter_svg: ^0.22.0
  # glassmorphism_ui: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/